version: "3.1"

services:
  #PotsgreSQL database service for local development.
  postgres:
    image: postgres:13.4
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  # end of postgres

  #Django Rest Api application.
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_service
    restart: on-failure
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    # command: tail -F anything
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
  # end of service

  # Redis
  redis:
    image: "redis:latest"
  # END OF Redis

  # Celery worker
  worker:
    image: django_service
    command: ["celery", "-A", "store_backend", "worker", "-l", "info"]
    # command: tail -F anything
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
  # END of Celery worker

  # Elasticsearch, Kibana
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - http.max_content_length=2000mb
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      SERVERNAME: kibana
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    ports:
      - 5601:5601
    networks:
      - elastic
  # End of Elasticsearch, Kibana

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
